### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by adityasingh22** [adityasingh22/Applinace-Energy-Prediction-Using-LSTM#1]
-Describe the Dataset used, a brief of how the data was collected, what the dataset contains
-Provide small notes on LSTM, ARIMA and FBPROPHET

**Comment by ashish-garg18** [comment]
What do we have to add in the Readme ? Can you please tell.

**Comment by adityasingh22** [comment]
I have updated the required fields, go through it, if you have any queries comment back
